spring:
  cloud:
    refresh:
      never-refreshable:
      extra-refreshable:
        - javax.sql.DataSource
        - com.zaxxer.hikari.HikariDataSource
  application:
    name: context-demo
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.id.new_generator_mappings: false
  datasource:
    hikari:
      allow-pool-suspension: true
    url: jdbc:postgresql://localhost:5432/database
    username: testuser
    password: testpw
    driver-class-name: org.postgresql.Driver
    continue-on-error: true

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - env

logging:
  level:
    org:
      springframework:
        context:
          support:
            DefaultLifecycleProcessor: debug

